### ISSUE TITLE
Clarification on the project

### ISSUE THREAD

**Issue by jgudavalli** [denismo/aws-iam-ldap-bridge#13]
Hello,
I am trying to set up an EC2 instance as a central machine that manages and controls access to all my other EC2 instances. 
Do I need to first install LDAP server on this and then use your plugin?

Regards,
Jyothi

**Comment by ambikads** [comment]
@denismo I encountered the same issue 
`ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)`

I do not want to use the pre-built AMI and want to configure in my ubuntu ec2 instance. I am using your latest binary package. Please advise. Thanks!!

**Comment by denismo** [comment]
This looks more like an infrastructure configuration issue. Is server running? Is it listening on the LDAP port? Is the port open in firewall? Is the port open in security group?

**Comment by ambikads** [comment]
I followed the exact steps listed above by Jyothi. Its an ubuntu ec2 instance, server is running, no firewall, port 10389 open in security group. any other ports needs to be opened? The issue you had mentioned with the partition, is that fixed?

**Comment by ambikads** [comment]
Is this how I start the server? How do I verify if its running? And what is an instance name?

~/apacheds/bin$ bash apacheds.sh
Usage: apacheds.sh [<instance name>] <action>
If <instance name> is ommited, 'default' will be used.
<action> is one of start, stop.
:~/apacheds/bin$ bash apacheds.sh start
Starting ApacheDS instance 'default'...

**Comment by ambikads** [comment]
@denismo I think I found the problem. Its because apacheds expects java to be under /bin/java while mine was user /usr/bin/java. Once I symlinked, I see the server is running.
However I see the below error with a custom rootDN in /etc/iam_ldap.conf. Please let me know if I should start a new thread. Thanks for your help.

`org.apache.direc
 tory.api.ldap.model.message.SearchRequestImpl@8623823: ERR_268 Cannot find a
  partition for dc=test,dc=ldap,dc=com`

With the default rootDN, I see this after running the ldapsearch command

` ldapsearch -H ldap://localhost:10389 -D "uid=admin,ou=system" -x -w secret -b "dc=iam,dc=aws,dc=org" "(objectclass=posixaccount)"`

````
# extended LDIF
#
# LDAPv3
# base <dc=iam,dc=aws,dc=org> with scope subtree
# filter: (objectclass=posixaccount)
# requesting: ALL
#

# search result
search: 2
result: 0 Success

# numResponses: 1``
````

**Comment by denismo** [comment]
it's hard to tell. The root DN is created on start, whether it is default or custom. Do you see any exceptions in the log?
