### ISSUE TITLE
Groups not updating properly in LDAP

### ISSUE THREAD

**Issue by Shellcat-Zero** [denismo/aws-iam-ldap-bridge#18]
If a new group is added in IAM, and an existing user is added to this group, the group will appear in the LDAP but with no users in it.  Additionally, if a user is removed from a group in IAM, LDAP does not update the group to show that the user is removed from it.

Is there a setting in iam.ldif or /etc/iam_ldap.conf that I'm missing?

**Comment by denismo** [comment]
Sounds more like a bug, there is a regular update task which should take care of all of that.

**Comment by Shellcat-Zero** [comment]
Ok, thanks, I'll see if I can build the source to try to debug the issue.

**Comment by Shellcat-Zero** [comment]
I've been going through the code, can you point out where the update task is located?  Also, I cannot find the AMI that you mention in the install instructions, does it still exist?

**Comment by denismo** [comment]
check src/com/denismo/aws/iam/LDAPIAMPoller.java. 
pollIAM is the method which is called repeatedly, and it performs updates as necessary.

**Comment by Shellcat-Zero** [comment]
Thanks Denis.  I also found your pre-built AMIs in the Sydney zone :)

**Comment by denismo** [comment]
Ah, makes sense. Yes, I think I only produced AMI for ap-southeast-2 (that's where I am). Will update the documentation to reflect that. You should be able to copy though.

**Comment by james-dekker** [comment]
Hi Denis,

I too am experiencing the same issue that Shellcat-Zero reported. 

Decided to ask you several questions (by placing them in three sections) since they are co-related to the troubleshooting process. All apologies if this posting is a bit verbose.

I. Groups Not Updating Propertly
----------------------------------------

When I add users to more than one group it doesn't show via ldapsearch or getent group on my client machine.

For example, when I use AWS Console and create the following groups:

* testgroup1
* testgroup2

And then proceed by creating these users:

* testuser1 
* testuser2
* testuser3

Added them to both groups via AWS Console:

* testgroup1: testuser1, testuser2, testuser3
* testgroup2: testuser1, testuser2, testuser3

When I log into my Linux box which has LDAP client configuration setup and I do the following:
```
getent group
```
These are the results:
```
testgroup1:*:1014:testuser1,testuser2,testuser3
testgroup2:*:1015:
```
Notice how testgroup2 does not display my users?

Likewise, when I do an ldapsearch:
```
ldapsearch -H ldap://server_ip_address:10389 -D "uid=admin,ou=system" -x -w secret -b "dc=iam,dc=aws,dc=org" "(cn=testgroup2)"
```
I get an empty result set:
```
# extended LDIF

# LDAPv3
# base <dc=iam,dc=aws,dc=org> with scope subtree
# filter: (cn=testgroup2)
# requesting: ALL
#      
# testgroup2, groups, iam.aws.org

dn: cn=testgroup2,ou=groups,dc=iam,dc=aws,dc=org
objectClass: posixGroup
objectClass: iamgroup
objectClass: top
cn: testgroup2

gidNumber: 1015
# search result
search: 2
result: 0 Success
```
However, if I do an ldapsearch for testgroup1:
```
ldapsearch -H ldap://server_ip_address:10389 -D "uid=admin,ou=system" -x -w secret -b "dc=iam,dc=aws,dc=org" "(cn=testgroup1)"
```
Yields:

```
# extended LDIF
#

# LDAPv3
# base <dc=iam,dc=aws,dc=org> with scope subtree
# filter: (cn=testgroup1)
# requesting: ALL
#
# testgroup1, groups, iam.aws.org

dn: cn=testgroup1,ou=groups,dc=iam,dc=aws,dc=org
objectClass: posixGroup
objectClass: iamgroup
objectClass: top
cn: testgroup1
gidNumber: 1014

memberUid: testuser1
memberUid: testuser2
memberUid: testuser3

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```
Is this a bug in your aws-iam-ldap-bridge code or a configuration issue?

Tried it using ami-19533f23 you mentioned in the install instructions and am getting the same results.

II. Update to ApacheDS 2.0.0-M20?
--------------------------------------------

Perhaps this Groups bug is related to ApacheDS 2.0.0-M17? 

Are there any plans to update the aws-iam-ldap-bridge to run with ApacheDS 2.0.0-M20? 

I tried to build your aws-iam-ldap-bridge with ApachaeDS 2.0.0-M20 by using the following steps:

1. Downloaded the latest apacheds distribution ApacheDS 2.0.0-M20.

2. Renamed the top-level folder to apacheds

3. Copied / moved apacheds into /aws-iam-ldap-bridge/dist directory

4. Issuing ant dist 

It seems that the problems that exist are:

1. Older versions of ApacheDS were dependent on a JDK / JRE 1.6, whereas ApacheDS 2.0.0-M20 is dependent on JDK / JRE 1.7.

2. When I downloaded JDK 1.7 on my target LDAP server and changed the $JAVA_HOME to point ot JDK 1.7's root dir,

I was able to build the aws-iam-ldap-bridge by following the instructions above...

However the default.zip that comes bundled with your project has different iam.ldif configuration settings than the newest version (some entries are deprecated)...

Will be very grateful if you could indicate the correct process / procedure to upgrade this project against the newest version of ApacheDS 2.0.0-M20...

III. Debugging via Eclipse
---------------------------------
When I imported your project into Eclipse it reported that a lot of the Amazon code is deprecated...

How would you recommend debugging your code using Eclipse?

Am able to build your Apache-2.0.0-M17 code using Eclipse but was wondering if you can suggest a way to use the Apache Studio (locally) or a standalone apacheds server to debug your code?

What I want to do is:

1. Set breakpoints via Eclipse

2. Build your apacheds server (containing the bridge) using ant dist

3. Run it locally or remotely

4. Use various ldapsearch queries that would launch the Eclipse debugger.

May I ask you how you wrote this? Do you use an IDE or just a plain editor like vim and just use print statement and logging statements?

Thanks you very much for taking the time to read all of this. Sorry if it seems too thorough.

Again, thank you for creating the IAM-AWS-LDAP Bridge!

-JD

**Comment by denismo** [comment]
First of all - thanks for the detailed description. Let me take a look at this tonight.

**Comment by denismo** [comment]
So, answering the questions:
1. It is not bug a limitation of the current implementation - I retrieve only the first group (search for "primaryGroup"). I need to check if this can be changed, I'd presume (but don't remember) that this has something to do with the limitations inside of either LDAP/Posix schema or something else.

But if there are no limitations, I will fix it then.

2. Upgrading to the new version is problematic. As you noticed, the version are significantly different. I spent lots of time upgrading from M13 to M17, and don't want to go through that pain again. Unless it is super-critical. But I don't think the problems you are having are related to the ApacheDS version, so hopefully we don't need to upgrade.

I can upgrade to the newer AWS SDK, as part of the fix for #1.

3. I did run ApacheDS with the debugging option (JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=y") and then attach to it using IntelliJ

**Comment by denismo** [comment]
1) - Unfortunately, this is the limitation of the Posix schema:
dn: m-oid=1.3.6.1.1.1.1.1, ou=attributetypes, cn=nis, ou=schema
objectclass: metaAttributeType
objectclass: metaTop
objectclass: top
m-oid: 1.3.6.1.1.1.1.1
m-name: gidNumber
m-description: An integer uniquely identifying a group in an administrative doma
 in
m-equality: integerMatch
m-syntax: 1.3.6.1.4.1.1466.115.121.1.27
m-singleValue: TRUE

It allows only a single value for group ID. I'll check if this can be extended - I don't want to modify the embedded schema, but may be I can use another property as an extension.

**Comment by denismo** [comment]
So, according this: http://www.openldap.org/lists/openldap-software/200307/msg00735.html, it should be possible just to add the user to multiple groups (memberUid supports a list) and that should do it. So I'll implement that.

**Comment by denismo** [comment]
And I confirmed the problem with deleting users - they don't get removed from groups. Neither when they are deleted, nor when they are removed from a group.

**Comment by denismo** [comment]
I've implemented the logic fixing both problems (multiple groups and deletions), but ran out of time testing. Will continue over the weekend.

**Comment by james-dekker** [comment]
Thank you so much!

**Comment by denismo** [comment]
This should be fixed. Both cases - removal of user, or removal of user from a group. I uploaded apacheds-0.2.2.zip onto S3.

**Comment by denismo** [comment]
Also the case of multiple groups should be fixed as well

**Comment by Shellcat-Zero** [comment]
Thanks Denis!  I'll redeploy with your updates.
